-- นำเข้าคลังคำจริงของพี่กัน (จาก Google Doc) แทนคำตัวอย่าง
truncate wb_words restart identity;
delete from wb_novels;

insert into wb_words (text, meaning, category_id, subcategory, highlight, novel, reviewed, created_at) values
  ('เงาดำทะมึน',null,'c0','แสงและเงา',null,null,true,now() - interval '0 days'),
  ('เงาตะคุ่ม',null,'c0','แสงและเงา',null,null,true,now() - interval '1 days'),
  ('หลืบเงา',null,'c0','แสงและเงา',null,null,true,now() - interval '2 days'),
  ('ความมืดครึ้ม',null,'c0','แสงและเงา',null,null,true,now() - interval '3 days'),
  ('ความมืดสลัว',null,'c0','แสงและเงา',null,null,true,now() - interval '4 days'),
  ('เปลวไฟสว่างวาบ',null,'c0','แสงและเงา',null,null,true,now() - interval '5 days'),
  ('เปลวไฟที่ไหววูบวาบขจัดความมืด',null,'c0','แสงและเงา',null,null,true,now() - interval '6 days'),
  ('ฟ้าแลบแปลบปลาบ',null,'c0','แสงและเงา',null,null,true,now() - interval '7 days'),
  ('สลัวราง',null,'c0','แสงและเงา',null,null,true,now() - interval '8 days'),
  ('แสงไฟริบหรี่',null,'c0','แสงและเงา',null,null,true,now() - interval '9 days'),
  ('แสงดาวที่สาดส่องสลัว',null,'c0','แสงและเงา',null,null,true,now() - interval '10 days'),
  ('ภายใต้แสงสว่างไสว',null,'c0','แสงและเงา',null,null,true,now() - interval '11 days'),
  ('สว่างเรืองด้วยแสงอ่อน ๆ จากเปลวเทียนที่ไหววูบ',null,'c0','แสงและเงา','ไหววูบ',null,true,now() - interval '12 days'),
  ('ส่องสว่างวอมแวม',null,'c0','แสงและเงา','วอมแวม',null,true,now() - interval '13 days'),
  ('ลำแสงสีขาววาววับราวดาบคมกริบฟาดฟันลงมาในความมืด',null,'c0','แสงและเงา','วาววับ',null,true,now() - interval '14 days'),
  ('แสงสว่างยามรุ่งสางส่องผ่านผ้าม่านเบาบางเข้ามา',null,'c0','แสงและเงา',null,null,true,now() - interval '15 days'),
  ('เปลวเทียน',null,'c0','แสงและเงา',null,null,true,now() - interval '16 days'),
  ('เชิงเทียน',null,'c0','แสงและเงา',null,null,true,now() - interval '17 days'),
  ('โคมไฟระย้า',null,'c0','แสงและเงา',null,null,true,now() - interval '18 days'),
  ('สีดำปี๋',null,'c0','สี',null,null,true,now() - interval '19 days'),
  ('แดงเรื่อ',null,'c0','สี',null,null,true,now() - interval '20 days'),
  ('ขาวโพลน',null,'c0','สี',null,null,true,now() - interval '21 days'),
  ('สีดอกเลา',null,'c0','สี',null,null,true,now() - interval '22 days'),
  ('สีแดงแปร๊ด',null,'c0','สี',null,null,true,now() - interval '23 days'),
  ('สีชมพูเรื่อๆ',null,'c0','สี',null,null,true,now() - interval '24 days'),
  ('สีทึมๆ',null,'c0','สี',null,null,true,now() - interval '25 days'),
  ('สีซีด',null,'c0','สี',null,null,true,now() - interval '26 days'),
  ('อากาศเย็นชื้นและเหม็นอับ',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '27 days'),
  ('ฝุ่นจับขะมุกขะมอม',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '28 days'),
  ('โอ่อ่าอลังการ',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '29 days'),
  ('ละลานตา',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '30 days'),
  ('ทั่วสารทิศ',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '31 days'),
  ('อับทึบ',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '32 days'),
  ('พลัดหลง','ในฉาก','c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '33 days'),
  ('ม่านหมอก',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '34 days'),
  ('ท้องฟ้าขมุกขมัว',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '35 days'),
  ('ความเวิ้งว้างว่างเปล่า',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '36 days'),
  ('โถงทางเดินที่ทอดยาว',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '37 days'),
  ('บันไดแคบชัน',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '38 days'),
  ('ประตูที่แง้มอยู่',null,'c0','สภาพแวดล้อมและบรรยากาศ','แง้ม',null,true,now() - interval '39 days'),
  ('บันไดแคบๆทอดขึ้น',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '40 days'),
  ('คฤหาสน์ที่ใหญ่โตโก้หรู',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '41 days'),
  ('ละแวกบ้าน',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '42 days'),
  ('ตึกรามบ้านช่อง',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '43 days'),
  ('ห้องกว้างมืดทึบ',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '44 days'),
  ('กรุกระจก',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '45 days'),
  ('ลอดโพรง',null,'c0','สภาพแวดล้อมและบรรยากาศ','โพรง',null,true,now() - interval '46 days'),
  ('เชิงบันได',null,'c0','สภาพแวดล้อมและบรรยากาศ',null,null,true,now() - interval '47 days'),
  ('จะพังมิพังแหล่',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '48 days'),
  ('รูโหว่',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '49 days'),
  ('ขื่อเปลือย',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '50 days'),
  ('หยากไย่',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '51 days'),
  ('พื้นกระดานที่ทรุดยวบ',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '52 days'),
  ('อาคารโย้เย้จวนถล่ม',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '53 days'),
  ('หักโค่น',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '54 days'),
  ('ราวไม้ที่หักสะบั้น',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '55 days'),
  ('ล้มระเนระนาด',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '56 days'),
  ('ซากปรักหักพังกลืนร่าง',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '57 days'),
  ('ถูกเหยียบย่ำยับเยิน',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '58 days'),
  ('รอยเท้าทับซ้อนพลวันกันไปมา',null,'c0','ความเก่า ความเสียหาย และร่องรอย',null,null,true,now() - interval '59 days'),
  ('แมกไม้ที่แกว่งไกว',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '60 days'),
  ('แมกไม้เบียดเสียด',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '61 days'),
  ('พงหญ้า',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '62 days'),
  ('ป่ามืดทึบ',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '63 days'),
  ('หมู่ไม้หนาทึบ',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '64 days'),
  ('ทึ้งเถากุหลาบ',null,'c0','ธรรมชาติและสภาพอากาศ','เถากุหลาบ',null,true,now() - interval '65 days'),
  ('แมกไม้เขียวชอุ่ม',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '66 days'),
  ('ป่าเขาลำเนาไพร',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '67 days'),
  ('ไหวสะเทือนเป็นระลอกคลื่น',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '68 days'),
  ('เชิงผา',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '69 days'),
  ('สายลมพัดพรูเข้ามา',null,'c0','ธรรมชาติและสภาพอากาศ','พัดพรู',null,true,now() - interval '70 days'),
  ('สายลมที่พัดมาลูบไล้แก้ม',null,'c0','ธรรมชาติและสภาพอากาศ','ลูบไล้',null,true,now() - interval '71 days'),
  ('แมลงบินว่อน',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '72 days'),
  ('กระเพื่อมขึ้นลงตามระลอกคลื่น',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '73 days'),
  ('ดวงจันทร์สีซีดคล้อยต่ำอยู่บนท้องฟ้า',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '74 days'),
  ('ท้องฟ้าคำรามเสียงดังลั่น',null,'c0','ธรรมชาติและสภาพอากาศ','ท้องฟ้า',null,true,now() - interval '75 days'),
  ('ฝนกระหน่ำ',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '76 days'),
  ('เสียงฟ้าคำรามกึกก้อง',null,'c0','ธรรมชาติและสภาพอากาศ',null,null,true,now() - interval '77 days'),
  ('ยามวิกาล',null,'c0','ช่วงเวลา',null,null,true,now() - interval '78 days'),
  ('ดึก ๆ ดื่น ๆ',null,'c0','ช่วงเวลา',null,null,true,now() - interval '79 days'),
  ('ความมืดมิดในยามราตรี',null,'c0','ช่วงเวลา',null,null,true,now() - interval '80 days'),
  ('ดวงอาทิตย์ลับขอบฟ้า',null,'c0','ช่วงเวลา',null,null,true,now() - interval '81 days'),
  ('ทุ่มเศษ',null,'c0','ช่วงเวลา',null,null,true,now() - interval '82 days'),
  ('ราวทุ่มครึ่ง',null,'c0','ช่วงเวลา',null,null,true,now() - interval '83 days'),
  ('ปาไปหนึ่งวัน',null,'c0','ช่วงเวลา',null,null,true,now() - interval '84 days'),
  ('รุ่งเช้า',null,'c0','ช่วงเวลา',null,null,true,now() - interval '85 days'),
  ('ไม่ทันกาล',null,'c0','ช่วงเวลา',null,null,true,now() - interval '86 days'),
  ('แสงสว่างยามรุ่งสาง',null,'c0','ช่วงเวลา',null,null,true,now() - interval '87 days'),
  ('ใบหน้าผอมเรียวยับย่น',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '88 days'),
  ('ใบหน้าเรียวคางแหลม',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '89 days'),
  ('ใบหน้าซีดเผือดม',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '90 days'),
  ('จิ้มลิ้มพริ้มเพรา',null,'c1','ใบหน้าและโครงหน้า','จิ้มลิ้มพริ้มเพรา',null,true,now() - interval '91 days'),
  ('หน้าตาสะสวย',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '92 days'),
  ('ใบหน้าซูบซีด',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '93 days'),
  ('หน้าผากกว้าง',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '94 days'),
  ('แนวคิ้วที่พาดยาว',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '95 days'),
  ('จมูกขนาดใหญ่งุ้มงอเหมือนนกอินทรี',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '96 days'),
  ('ริมฝีปากสีแดงจิ้มลิ้ม',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '97 days'),
  ('ริมฝีปากอันแห้งผาก',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '98 days'),
  ('ริมฝีปากหนาซีดขาวไร้เลือด',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '99 days'),
  ('เขี้ยวแหลมคม',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '100 days'),
  ('แก้มซูบ',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '101 days'),
  ('แก้มตอบ',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '102 days'),
  ('คางเรียว',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '103 days'),
  ('คางแหลม',null,'c1','ใบหน้าและโครงหน้า',null,null,true,now() - interval '104 days'),
  ('ดวงตาเรียวเล็ก',null,'c1','ดวงตา',null,null,true,now() - interval '105 days'),
  ('ดวงตากลมโตเป็นประกายด้วยความตื่นเต้น',null,'c1','ดวงตา',null,null,true,now() - interval '106 days'),
  ('ตาแดงเรื่อ',null,'c1','ดวงตา',null,null,true,now() - interval '107 days'),
  ('ดวงตาสีน้ำตาลเข้มที่มีประกายแข็งกร้าว',null,'c1','ดวงตา',null,null,true,now() - interval '108 days'),
  ('ดวงตาเป็นประกายสุกใส',null,'c1','ดวงตา',null,null,true,now() - interval '109 days'),
  ('ดวงตาบวมแดงจากการร้องไห้',null,'c1','ดวงตา',null,null,true,now() - interval '110 days'),
  ('คลอด้วยน้ำตา',null,'c1','ดวงตา',null,null,true,now() - interval '111 days'),
  ('น้ำตาร่วงเผาะ',null,'c1','ดวงตา',null,null,true,now() - interval '112 days'),
  ('ขอบตาคล้ำจัด',null,'c1','ดวงตา',null,null,true,now() - interval '113 days'),
  ('ลูกตาถูกควัก',null,'c1','ดวงตา','ลูกตา',null,true,now() - interval '114 days'),
  ('เบ้าตา',null,'c1','ดวงตา',null,null,true,now() - interval '115 days'),
  ('คอระหงขาวนวล',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '116 days'),
  ('พริ้มเพรา',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '117 days'),
  ('วงแขน',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '118 days'),
  ('วงแขนแข็งแกร่ง',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '119 days'),
  ('มืออันหยาบกร้าน',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '120 days'),
  ('นิ้วมือห้อยลงไปเรี่ยกับพื้น',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '121 days'),
  ('หน้าแข้งลีบๆ',null,'c1','ร่างกายและรูปร่าง','หน้าแข้ง',null,true,now() - interval '122 days'),
  ('ผอมบาง',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '123 days'),
  ('ร่างสูงล่ำสัน',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '124 days'),
  ('ร่างกำยำ',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '125 days'),
  ('ชายร่างใหญ่',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '126 days'),
  ('ร่างบึกบึน',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '127 days'),
  ('ชายร่างล่ำสัน',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '128 days'),
  ('ผ่ายผอม',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '129 days'),
  ('อ่อนปวกเปียก',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '130 days'),
  ('รูปร่างพิกลพิการ',null,'c1','ร่างกายและรูปร่าง',null,null,true,now() - interval '131 days'),
  ('ขาวซีด',null,'c1','สีผิว',null,null,true,now() - interval '132 days'),
  ('ซีดเผือด',null,'c1','สีผิว',null,null,true,now() - interval '133 days'),
  ('ซีดขาวไร้เลือด',null,'c1','สีผิว',null,null,true,now() - interval '134 days'),
  ('ผมขาวโพลน',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '135 days'),
  ('ผมสยายยาว',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '136 days'),
  ('ผมยาวสีดอกเลา',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '137 days'),
  ('รุงรังไปด้วยหนวดเครา',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '138 days'),
  ('ผมเผ้ายุ่งเหยิง',null,'c1','เส้นผม/ขน/หนวด','ผมเผ้ายุ่งเหยิง',null,true,now() - interval '139 days'),
  ('ขนสีดำหนาทึบ',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '140 days'),
  ('ผมยาวสลวยพลิ้วไปตามสายลมอ่อนๆ',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '141 days'),
  ('หนวดเคราปรกหน้ารุงรัง',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '142 days'),
  ('ผมเผ้าหนวดเครารุงรัง',null,'c1','เส้นผม/ขน/หนวด',null,null,true,now() - interval '143 days'),
  ('สารรูป',null,'c1','สภาพร่างกาย',null,null,true,now() - interval '144 days'),
  ('ทรุดโทรม',null,'c1','สภาพร่างกาย',null,null,true,now() - interval '145 days'),
  ('อิดโรย',null,'c1','สภาพร่างกาย','อิดโรย',null,true,now() - interval '146 days'),
  ('สกปรกเลอะเทอะ',null,'c1','สภาพร่างกาย',null,null,true,now() - interval '147 days'),
  ('เมามาย',null,'c1','สภาพร่างกาย',null,null,true,now() - interval '148 days'),
  ('ดูผิดแปลกจากยามปกติ',null,'c1','สภาพร่างกาย',null,null,true,now() - interval '149 days');

insert into wb_words (text, meaning, category_id, subcategory, highlight, novel, reviewed, created_at) values
  ('บาดแผลเหวอะหวะ',null,'c1','ร่องรอย/บาดแผล',null,null,true,now() - interval '150 days'),
  ('ใบหน้าโชกเลือด',null,'c1','ร่องรอย/บาดแผล',null,null,true,now() - interval '151 days'),
  ('เลือดไหลนอง',null,'c1','ร่องรอย/บาดแผล',null,null,true,now() - interval '152 days'),
  ('แผลฉกรรจ์',null,'c1','ร่องรอย/บาดแผล',null,null,true,now() - interval '153 days'),
  ('โหม่งโขดหินจนศีรษะแตก',null,'c1','ร่องรอย/บาดแผล','ศีรษะแตก',null,true,now() - interval '154 days'),
  ('ท้องแตกไส้ทะลัก',null,'c1','สภาพความตายและความสยดสยอง',null,null,true,now() - interval '155 days'),
  ('คอหักพับลงไปที่บ่า',null,'c1','สภาพความตายและความสยดสยอง',null,null,true,now() - interval '156 days'),
  ('คอหักบิดเบี้ยว',null,'c1','สภาพความตายและความสยดสยอง',null,null,true,now() - interval '157 days'),
  ('ถูกรถทับบี้แบน',null,'c1','สภาพความตายและความสยดสยอง',null,null,true,now() - interval '158 days'),
  ('สภาพที่ยับเยิน',null,'c1','สภาพความตายและความสยดสยอง',null,null,true,now() - interval '159 days'),
  ('ร่างไร้วิญญาณ',null,'c1','สภาพความตายและความสยดสยอง',null,null,true,now() - interval '160 days'),
  ('นอนหงายนิ่งสนิทไม่ไหวติง',null,'c1','สภาพความตายและความสยดสยอง',null,null,true,now() - interval '161 days'),
  ('เปรอะเปื้อน',null,'c1','ความสะอาด/ความเรียบร้อย',null,null,true,now() - interval '162 days'),
  ('มอมแมม',null,'c1','ความสะอาด/ความเรียบร้อย','มอมแมม',null,true,now() - interval '163 days'),
  ('ยุ่งเหยิง',null,'c1','ความสะอาด/ความเรียบร้อย',null,null,true,now() - interval '164 days'),
  ('ตาเบิกกว้าง',null,'c2','สายตาและการมอง',null,null,true,now() - interval '165 days'),
  ('เบิกตาโพลง',null,'c2','สายตาและการมอง',null,null,true,now() - interval '166 days'),
  ('เบิกตาโต',null,'c2','สายตาและการมอง',null,null,true,now() - interval '167 days'),
  ('เบิกตาโตด้วยความตกใจ',null,'c2','สายตาและการมอง',null,null,true,now() - interval '168 days'),
  ('เบิกตาอย่างหวาดๆ',null,'c2','สายตาและการมอง',null,null,true,now() - interval '169 days'),
  ('ยืนตาค้างด้วยความตะลึง',null,'c2','สายตาและการมอง',null,null,true,now() - interval '170 days'),
  ('จ้องเขม็ง',null,'c2','สายตาและการมอง',null,null,true,now() - interval '171 days'),
  ('จ้องตาขวาง',null,'c2','สายตาและการมอง',null,null,true,now() - interval '172 days'),
  ('ถลึงตาตอบ',null,'c2','สายตาและการมอง',null,null,true,now() - interval '173 days'),
  ('สายตาเย็นชาแฝงแววดูถูก',null,'c2','สายตาและการมอง',null,null,true,now() - interval '174 days'),
  ('ทำตาหยีเป็นเส้นตรง',null,'c2','สายตาและการมอง',null,null,true,now() - interval '175 days'),
  ('หรี่ตาตอบ',null,'c2','สายตาและการมอง',null,null,true,now() - interval '176 days'),
  ('สายตาคาดคั้น',null,'c2','สายตาและการมอง',null,null,true,now() - interval '177 days'),
  ('จ้องมองด้วยสายตาเคลือบแคลงสงสัย',null,'c2','สายตาและการมอง',null,null,true,now() - interval '178 days'),
  ('สายตาที่แหลมคม',null,'c2','สายตาและการมอง',null,null,true,now() - interval '179 days'),
  ('ทำตาวาว',null,'c2','สายตาและการมอง',null,null,true,now() - interval '180 days'),
  ('ดวงตากลมโตเป็นประกายด้วยความตื่นเต้น',null,'c2','สายตาและการมอง',null,null,true,now() - interval '181 days'),
  ('ทำตาลอย',null,'c2','สายตาและการมอง',null,null,true,now() - interval '182 days'),
  ('นั่งตาลอยคว้าง',null,'c2','สายตาและการมอง',null,null,true,now() - interval '183 days'),
  ('ใบหน้านิ่งเฉยไร้ความรู้สึก',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '184 days'),
  ('ตีหน้าเฉยชา',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '185 days'),
  ('ตีหน้าเฉยเมย',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '186 days'),
  ('ทำหน้าขรึม',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '187 days'),
  ('นั่งฟังอย่างหน้าตาเฉย',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '188 days'),
  ('ใบหน้าบึ้งตึง',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '189 days'),
  ('ปั้นหน้าเครียด',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '190 days'),
  ('ทำหน้านิ่วคิ้วขมวด',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '191 days'),
  ('ใบหน้ากระตุกถี่',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '192 days'),
  ('ขมวดคิ้ว',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '193 days'),
  ('นิ่วหน้าจนเห็นรอยลึก',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '194 days'),
  ('ใบหน้าซูบซีด',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '195 days'),
  ('หน้าซีดตัวสั่น',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '196 days'),
  ('ใบหน้ากระตุกและบิดเบี้ยวน่าเกลียดน่ากลัว',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '197 days'),
  ('ทำหน้าฉงน',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '198 days'),
  ('ทำหน้าเชื่อครึ่งไม่เชื่อครึ่ง',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '199 days'),
  ('ฉายชัดอยู่บนใบหน้า',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '200 days'),
  ('ยิ้มอย่างอ่อนโยน',null,'c2','การแสดงออกทางใบหน้าและศีรษะ',null,null,true,now() - interval '201 days'),
  ('ลูบไล้แก้ม',null,'c2','การขยับแขนและมือ','ลูบไล้',null,true,now() - interval '202 days'),
  ('ยื่นมือไปกระชาก',null,'c2','การขยับแขนและมือ','กระชาก',null,true,now() - interval '203 days'),
  ('ปัดป่ายมือสองข้างไปมา',null,'c2','การขยับแขนและมือ','ปัดป่าย',null,true,now() - interval '204 days'),
  ('กุมแขน',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '205 days'),
  ('กระชับมือ',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '206 days'),
  ('กระชับแฟ้มเอกสาร',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '207 days'),
  ('ทึ้งเถากุหลาบ',null,'c2','การขยับแขนและมือ','ทึ้ง',null,true,now() - interval '208 days'),
  ('ลูกตาถูกควัก',null,'c2','การขยับแขนและมือ','ควัก',null,true,now() - interval '209 days'),
  ('ควานหา',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '210 days'),
  ('เงื้อสุดแขน',null,'c2','การขยับแขนและมือ','เงื้อ',null,true,now() - interval '211 days'),
  ('มือยกขึ้นไขว่คว้าอากาศ',null,'c2','การขยับแขนและมือ','ยกขึ้นไขว่คว้า',null,true,now() - interval '212 days'),
  ('แขนซึ่งกางอ้าซ่า',null,'c2','การขยับแขนและมือ','กางอ้าซ่า',null,true,now() - interval '213 days'),
  ('เท้าสะเอว',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '214 days'),
  ('กอดเข่า',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '215 days'),
  ('ไขว้แขน',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '216 days'),
  ('ตบเข่าฉาด',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '217 days'),
  ('อ้าแขนกว้างกั้นไว้',null,'c2','การขยับแขนและมือ','อ้าแขน',null,true,now() - interval '218 days'),
  ('ดีดปลายเล็บยาวแปร๊ดกับขอบโต๊ะ',null,'c2','การขยับแขนและมือ','ดีดปลายเล็บ',null,true,now() - interval '219 days'),
  ('นิ้วมือห้อยลงไปเรี่ยกับพื้น',null,'c2','การขยับแขนและมือ','นิ้วมือห้อย',null,true,now() - interval '220 days'),
  ('โอบอุ้ม',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '221 days'),
  ('คลายวงแขนที่รัดตัวเธอ',null,'c2','การขยับแขนและมือ','คลายวงแขน',null,true,now() - interval '222 days'),
  ('พยุงให้ลุกขึ้น',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '223 days'),
  ('ฉุดลาก',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '224 days'),
  ('ดุนหลัง',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '225 days'),
  ('รุนหลัง',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '226 days'),
  ('เงื้อแผ่นไม้ในมือ',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '227 days'),
  ('หามศพ',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '228 days'),
  ('เหวี่ยง',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '229 days'),
  ('ฟาดฟัน',null,'c2','การขยับแขนและมือ',null,null,true,now() - interval '230 days'),
  ('เหยียบย่าง',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '231 days'),
  ('เดินอย่างระมัดระวังทุกฝีก้าว',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '232 days'),
  ('หยั่งฝีเท้าทดสอบ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '233 days'),
  ('เที่ยวเตร่',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '234 days'),
  ('ดูลาดเลา',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '235 days'),
  ('ย่างเท้า',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '236 days'),
  ('เดินดุ่มๆ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '237 days'),
  ('เดินตัดสวน',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '238 days'),
  ('เดินเฉียด',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '239 days'),
  ('ย่องอย่างเงียบกริบ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '240 days'),
  ('ปลีกตัว',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '241 days'),
  ('ลอดโพรง',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '242 days'),
  ('ลอด',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '243 days'),
  ('เร่งฝีเท้า',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '244 days'),
  ('วิ่งกวด',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '245 days'),
  ('วิ่งปราด',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '246 days'),
  ('วิ่งเหยาะๆ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '247 days'),
  ('ผลุนผลันออกจากห้อง',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '248 days'),
  ('กระโจน',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '249 days'),
  ('กระโจนเข้าไปในห้อง',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '250 days'),
  ('กระโจนออกจากประตู',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '251 days'),
  ('พุ่งเข้าไปกระแทกท้อง',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '252 days'),
  ('ตรงดิ่งไปยัง',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '253 days'),
  ('ปราดเข้าไปหา',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '254 days'),
  ('ปราดไปที่ริมระเบียง',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '255 days'),
  ('มุ่งหน้า',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '256 days'),
  ('บึ่งรถมา',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '257 days'),
  ('ลื่นไถล',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '258 days'),
  ('เซถลาเข้ามาราวกับถูกผลัก',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '259 days'),
  ('กระเสือกกระสน',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '260 days'),
  ('ซมซานจากไป',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '261 days'),
  ('เดินโซเซ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '262 days'),
  ('วิ่งโซซัดโซเซ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '263 days'),
  ('แข้งขาปัดเป๋',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '264 days'),
  ('ทรุดตัวลงนั่งแหมะ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '265 days'),
  ('ยืนโอนเอน',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '266 days'),
  ('ทรงตัวอย่างหมิ่นเหม่เสียสมดุล',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '267 days'),
  ('ร่างลอยละลิ่ว',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '268 days'),
  ('ถลาล้มทับ',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '269 days'),
  ('ล้มระเนระนาด',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '270 days'),
  ('กระทุ้งเข่า',null,'c2','การเคลื่อนที่/ฝีเท้า/ขา',null,null,true,now() - interval '271 days'),
  ('ซักไซ้',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '272 days'),
  ('ถามซักไซ้',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '273 days'),
  ('สำทับกำชับ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '274 days'),
  ('บอกซ้ำ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '275 days'),
  ('ย้ำ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '276 days'),
  ('สอดรู้สอดเห็น',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '277 days'),
  ('เลียบเคียงถาม',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '278 days'),
  ('คะยั้นคะยอ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '279 days'),
  ('ถามนั่นถามนี่',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '280 days'),
  ('คาดคั้น',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '281 days'),
  ('คาดคั้นเสียงแข็ง',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '282 days'),
  ('พร่ำถามตัวเอง',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '283 days'),
  ('บ่นเสียยืดยาว',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '284 days'),
  ('บ่นพึมพำ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '285 days'),
  ('พร่ำบ่นนั่นนี่',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '286 days'),
  ('พร่ำพูดพร่ำบอก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '287 days'),
  ('พร่ำเอ่ย',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '288 days'),
  ('พร่ำเรียก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '289 days'),
  ('โพล่งออกมา',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '290 days'),
  ('โพล่งขึ้น',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '291 days'),
  ('หลุดปาก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '292 days'),
  ('พลั้งปาก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '293 days'),
  ('กระแอมกระไอ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '294 days'),
  ('ด่าทออย่างสาดเสียเทเสีย',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '295 days'),
  ('ดุด่า',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '296 days'),
  ('กระแนะกระแหน',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '297 days'),
  ('ตวาดเสียงดังกึกก้อง',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '298 days'),
  ('ไล่ตะเพิด',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '299 days');

insert into wb_words (text, meaning, category_id, subcategory, highlight, novel, reviewed, created_at) values
  ('ปรามเสียงเรียบ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '0 days'),
  ('ตัดพ้อปีนเกลียว',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '1 days'),
  ('โต้กลับด้วยเสียงเฉียบขาด',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '2 days'),
  ('ปฏิเสธเสียงแข็ง',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '3 days'),
  ('ปรักปรำ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '4 days'),
  ('พูดจี้ใจดำ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '5 days'),
  ('เธอไม่ต่อปากต่อคำอะไรด้วยทั้งนั้น',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '6 days'),
  ('คัดค้าน',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '7 days'),
  ('พูดรัวเร็ว',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '8 days'),
  ('เล่าเสียงเนิบๆ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '9 days'),
  ('พูดห้วนๆ',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '10 days'),
  ('อ้ำอึ้ง',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '11 days'),
  ('ไม่ปริปาก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '12 days'),
  ('เอ่ยปาก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '13 days'),
  ('ละล่ำละลัก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '14 days'),
  ('ท่าทีอึกอัก',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '15 days'),
  ('พูดอ้อมค้อม',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '16 days'),
  ('กลบเกลื่อน',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '17 days'),
  ('เกลี้ยกล่อม',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '18 days'),
  ('บุ้ยใบ้','บอกใบ้','c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '19 days'),
  ('เออออ','คล้อยตาม','c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '20 days'),
  ('ซุบซิบนินทา',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '21 days'),
  ('เล่าลือกัน',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '22 days'),
  ('ขนานนาม',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '23 days'),
  ('พูดจาแทะโลม',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '24 days'),
  ('หว่านเสน่ห์',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '25 days'),
  ('เยี่ยมเยียน',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '26 days'),
  ('จัดแจง',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '27 days'),
  ('จับจอง',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '28 days'),
  ('ซุกซ่อน',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '29 days'),
  ('ห้อมล้อม',null,'c2','การสื่อสารและพฤติกรรมทางสังคม',null,null,true,now() - interval '30 days'),
  ('นั่งคุดคู้',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '31 days'),
  ('นั่งตัวลีบ',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '32 days'),
  ('นั่งยอง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '33 days'),
  ('นั่งปักหลัก',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '34 days'),
  ('นั่งห่อตัว',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '35 days'),
  ('ซุกตัวอยู่ในโซฟา',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '36 days'),
  ('ขนาบข้าง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '37 days'),
  ('ทรุดตัวลงนั่ง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '38 days'),
  ('ทรุดตัวลงนั่งยอง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '39 days'),
  ('ทิ้งตัวลงบนโซฟา',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '40 days'),
  ('นั่งห้อยขา',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '41 days'),
  ('ห่อไหล่',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '42 days'),
  ('ชันเข่าขึ้น',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '43 days'),
  ('ผุดลุกขึ้นจากเตียง',null,'c2','ท่าทางและภาพรวมร่างกาย','ผุดลุกขึ้น',null,true,now() - interval '44 days'),
  ('ผุดลุกขึ้นยืน',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '45 days'),
  ('เด้งตัวขึ้นจากเตียง',null,'c2','ท่าทางและภาพรวมร่างกาย','เด้งตัวขึ้น',null,true,now() - interval '46 days'),
  ('ยันตัวขึ้นนั่ง',null,'c2','ท่าทางและภาพรวมร่างกาย','ยันตัวขึ้น',null,true,now() - interval '47 days'),
  ('ยืดตัวขึ้น',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '48 days'),
  ('หันขวับไป',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '49 days'),
  ('หมุนตัวกลับ',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '50 days'),
  ('หมุนติ้ว',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '51 days'),
  ('ชะโงกหน้า',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '52 days'),
  ('ย่อตัวลง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '53 days'),
  ('เขยื่อน',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '54 days'),
  ('ชะงัก',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '55 days'),
  ('ชะงักกลางคัน',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '56 days'),
  ('หยุดกึก',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '57 days'),
  ('ผงะถอยหลัง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '58 days'),
  ('คล่องแคล่วกระฉับกระเฉง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '59 days'),
  ('กิริยาอันนุ่มนวล',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '60 days'),
  ('ยืนนิ่งขึง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '61 days'),
  ('ดิ้นรนขัดขืน',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '62 days'),
  ('เกร็งตัวแข็งขืน',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '63 days'),
  ('แอ่นอก',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '64 days'),
  ('แสดงอารมณ์โกรธเกรี้ยวรุนแรง',null,'c2','ท่าทางและภาพรวมร่างกาย',null,null,true,now() - interval '65 days'),
  ('แนบชิด',null,'c2','สัมผัส',null,null,true,now() - interval '66 days'),
  ('ริมฝีปากซุกไซ้',null,'c2','สัมผัส',null,null,true,now() - interval '67 days'),
  ('โผเข้าซบอก',null,'c2','สัมผัส',null,null,true,now() - interval '68 days'),
  ('ทาบทับ',null,'c2','สัมผัส',null,null,true,now() - interval '69 days'),
  ('นอนตัวแข็งทื่อ',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '70 days'),
  ('นอนแผ่หลา',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '71 days'),
  ('หงายหลังลงไปนอนแผ่หลา',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '72 days'),
  ('นอนหงายไม่ไหวติง',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '73 days'),
  ('นอนหงายนิ่งสนิทไม่ไหวติง',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '74 days'),
  ('แน่นิ่ง',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '75 days'),
  ('นอนเหยียดยาว',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '76 days'),
  ('แข็งทื่อ',null,'c2','ท่านอนและการหยุดนิ่ง',null,null,true,now() - interval '77 days'),
  ('เสียงพื้นไม้ลั่นเอี๊ยดอ๊าด',null,'c3','เสียงไม้/พื้น',null,null,true,now() - interval '78 days'),
  ('เสียงพื้นกระดานดังเอี๊ยดอ๊าด',null,'c3','เสียงไม้/พื้น',null,null,true,now() - interval '79 days'),
  ('เสียงไม้หักดัง กร๊อบ',null,'c3','เสียงไม้/พื้น',null,null,true,now() - interval '80 days'),
  ('ดังกรอบแกรบ',null,'c3','เสียงไม้/พื้น',null,null,true,now() - interval '81 days'),
  ('เสียงดัง แก๊ก',null,'c3','เสียงกลไก/เสียดสี',null,null,true,now() - interval '82 days'),
  ('ส่งเสียงครืดคราด',null,'c3','เสียงกลไก/เสียดสี',null,null,true,now() - interval '83 days'),
  ('โพละ',null,'c3','เสียงแตกหัก/ตกกระทบ',null,null,true,now() - interval '84 days'),
  ('หล่นตุ้บ',null,'c3','เสียงแตกหัก/ตกกระทบ',null,null,true,now() - interval '85 days'),
  ('ครึกโครม',null,'c3','เสียงแตกหัก/ตกกระทบ',null,null,true,now() - interval '86 days'),
  ('ปิดดังปัง',null,'c3','เสียงวัตถุ',null,null,true,now() - interval '87 days'),
  ('ส่งเสียงซู่ซ่า','ฝนตก/น้ำไหล/ป่าไม้','c3','เสียงธรรมชาติและของเหลว',null,null,true,now() - interval '88 days'),
  ('กระเซ็น','เสียงน้ำ','c3','เสียงธรรมชาติและของเหลว',null,null,true,now() - interval '89 days'),
  ('เสียงน้ำหยดติ๋งๆ',null,'c3','เสียงธรรมชาติและของเหลว',null,null,true,now() - interval '90 days'),
  ('เสียงฝีเท้า',null,'c3','เสียงจากการเคลื่อนไหวและร่างกาย',null,null,true,now() - interval '91 days'),
  ('เผียะ','เสียงฝ่ามือ','c3','เสียงจากการเคลื่อนไหวและร่างกาย',null,null,true,now() - interval '92 days'),
  ('สวบสาบ','เสียงเดินลุยหญ้า/ผ้าเสียดสี','c3','เสียงจากการเคลื่อนไหวและร่างกาย',null,null,true,now() - interval '93 days'),
  ('เสียงตบเข่าฉาด',null,'c3','เสียงจากการเคลื่อนไหวและร่างกาย',null,null,true,now() - interval '94 days'),
  ('ถ้อยคำที่ถ่อยสถุล',null,'c3','เสียงที่เปล่งจากปาก','ถ้อยคำ ถ่อยสถุล',null,true,now() - interval '95 days'),
  ('กระซิบกระซาบ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '96 days'),
  ('บ่นพึมพำ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '97 days'),
  ('พึมพำ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '98 days'),
  ('เสียงงึมงำ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '99 days'),
  ('ขู่ด้วยเสียงแหบแห้ง',null,'c3','เสียงที่เปล่งจากปาก','ขู่',null,true,now() - interval '100 days'),
  ('ตอบด้วยเสียงอ่อนระโหย',null,'c3','เสียงที่เปล่งจากปาก','ตอบ',null,true,now() - interval '101 days'),
  ('แผดเสียง',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '102 days'),
  ('แผดเสียงแหลมสูง',null,'c3','เสียงที่เปล่งจากปาก','แผดเสียง',null,true,now() - interval '103 days'),
  ('ร้องทักเสียงแหลมสูง',null,'c3','เสียงที่เปล่งจากปาก','เสียงแหลมสูง',null,true,now() - interval '104 days'),
  ('กรีดร้องโหยหวน',null,'c3','เสียงที่เปล่งจากปาก','กรีดร้อง',null,true,now() - interval '105 days'),
  ('เสียงแหลมสูงเหมือนไม่ใช่มนุษย์กรีดก้องออกมา',null,'c3','เสียงที่เปล่งจากปาก','กรีดก้อง',null,true,now() - interval '106 days'),
  ('กรีดร้องโหยหวนด้วยเสียงแหลมสูงราวกับว่าปอดถูกบีบคั้นสุดขีด',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '107 days'),
  ('ตวาดเสียงดังกึกก้อง',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '108 days'),
  ('เอะอะเอ็ดตะโร',null,'c3','เสียงที่เปล่งจากปาก','เอะอะ',null,true,now() - interval '109 days'),
  ('เอะอะโวยวาย',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '110 days'),
  ('เอะอะเสียงดัง',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '111 days'),
  ('ร้องโอดโอยเสียงลั่น',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '112 days'),
  ('นอนครวญคราง',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '113 days'),
  ('ครางเบาๆ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '114 days'),
  ('ครางเสียงแหบแห้ง',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '115 days'),
  ('ครางเสียงเบาหวิวแทบจะขาดห้วง',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '116 days'),
  ('ครางเสียงเศร้าและอึกอักราวกับมีเส้นด้ายพันอยู่ในลำคอ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '117 days'),
  ('เสียงสะอื้น',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '118 days'),
  ('สะอึกสะอื้น',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '119 days'),
  ('ร้องไห้คร่ำครวญ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '120 days'),
  ('ร้องไห้โฮ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '121 days'),
  ('ทำเสียงจิ๊ในปาก',null,'c3','เสียงที่เปล่งจากปาก','เสียงจิ๊',null,true,now() - interval '122 days'),
  ('ถอนหายใจเฮือกใหญ่',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '123 days'),
  ('ถอนใจ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '124 days'),
  ('กระแอมกระไอ',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '125 days'),
  ('เสียงโหยหวนชวนขนลุก',null,'c3','เสียงที่เปล่งจากปาก',null,null,true,now() - interval '126 days'),
  ('กระปรี้กระเปร่า',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '127 days'),
  ('น่ารื่นรมย์',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '128 days'),
  ('กระตือรือร้น',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '129 days'),
  ('เป็นห่วงเป็นใย',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '130 days'),
  ('น่ารักน่าเอ็นดู',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '131 days'),
  ('รักใคร่เอ็นดู',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '132 days'),
  ('เลือดเนื้อเชื้อไข','ความผูกพัน','c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '133 days'),
  ('บริสุทธิ์ผุดผ่อง',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '134 days'),
  ('ได้ใจ',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '135 days'),
  ('สงบเสงี่ยม',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '136 days'),
  ('เจียมเนื้อเจียมตัว',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '137 days'),
  ('สงบจิตสงบใจ',null,'c4','ใจเป็นปกติ - เป็นสุข',null,null,true,now() - interval '138 days'),
  ('ตัวสั่นสะท้าน',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '139 days'),
  ('สั่นระริก',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '140 days'),
  ('สั่นเทา',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '141 days'),
  ('ขยะแขยงจนขนลุกไปทั้งตัว',null,'c4','กายประท้วง - อาการทางร่าง','ขนลุกไปทั้งตัว',null,true,now() - interval '142 days'),
  ('ขนลุกเกรียว',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '143 days'),
  ('หน้าซีดตัวสั่น',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '144 days'),
  ('เจ็บแปลบ',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '145 days'),
  ('ลำคอกลับตีบตัน',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '146 days'),
  ('คลื่นเหียนวิงเวียน',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '147 days'),
  ('ตาฝาด',null,'c4','กายประท้วง - อาการทางร่าง',null,null,true,now() - interval '148 days'),
  ('น่าคลื่นเหียน',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '149 days');

insert into wb_words (text, meaning, category_id, subcategory, highlight, novel, reviewed, created_at) values
  ('น่าสมเพช',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '150 days'),
  ('น่าเวทนา',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '151 days'),
  ('น่าอนาถ',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '152 days'),
  ('แปลกพิกล',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '153 days'),
  ('โหดเหี้ยมเลือดเย็นน่าเกลียดน่ากลัว',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '154 days'),
  ('นังตัวดี',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '155 days'),
  ('ดูแคลน',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '156 days'),
  ('เหลวไหลไร้สาระ',null,'c4','ความรู้สึกต่อสิ่งอื่น/ผู้อื่น',null,null,true,now() - interval '157 days'),
  ('ครุ่นคิด',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '158 days'),
  ('คิดอะไรเรื่อยเปื่อย',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '159 days'),
  ('คร่ำเคร่ง','เครียด/จริงจัง','c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '160 days'),
  ('ปริศนาที่ต้องขบคิดอีกที',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '161 days'),
  ('ห้วงคิด',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '162 days'),
  ('ฟังอย่างใจจดใจจ่อ',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '163 days'),
  ('วาบขึ้นมาในใจ',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '164 days'),
  ('จริงดังคาด',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '165 days'),
  ('คลับคล้ายคลับคลา',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '166 days'),
  ('ลอยคว้างอยู่ในความทรงจำ',null,'c4','สภาวะทางความคิดและสมาธิ','ลอยคว้าง',null,true,now() - interval '167 days'),
  ('ภาพเหตุการณ์แวบขึ้นมา',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '168 days'),
  ('ติดตรึงอยู่ในใจ',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '169 days'),
  ('ท่องอยู่หลายเที่ยวจนจำได้ขึ้นใจ',null,'c4','สภาวะทางความคิดและสมาธิ',null,null,true,now() - interval '170 days'),
  ('ผ่านไปแค่อึดใจเดียว',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '171 days'),
  ('ครู่ก่อน',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '172 days'),
  ('หลายอึดใจ',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '173 days'),
  ('ครั้งคราว',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '174 days'),
  ('ซ้ำแล้วซ้ำอีก',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '175 days'),
  ('พร้อมเพรียงกัน',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '176 days'),
  ('พ้องกันอย่างน่าประหลาด',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '177 days'),
  ('รัวเร็ว',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '178 days'),
  ('ผลีผลาม',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '179 days'),
  ('ฉุกละหุก',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '180 days'),
  ('ชะงักกลางคัน',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '181 days'),
  ('ไม่ทันกาล',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '182 days'),
  ('ต่อหน้าต่อตา',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '183 days'),
  ('แต่ไหนแต่ไร',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '184 days'),
  ('หายสาบสูญ',null,'c5','ระยะเวลา จังหวะ และความเร็ว',null,null,true,now() - interval '185 days'),
  ('พาน','พานจะเกลียด','c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '186 days'),
  ('ระคน','รู้สึกปนกัน','c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '187 days'),
  ('แผ่ซ่านลามไปทั่วตัว',null,'c5','อาการและทิศทางของอารมณ์','ลามไปทั่วตัว',null,true,now() - interval '188 days'),
  ('แวบออกมาให้เห็นเป็นครั้งคราว',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '189 days'),
  ('วาบขึ้นมาในใจ',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '190 days'),
  ('ประดังประเด','ความรู้สึกรุมเร้าเข้ามา','c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '191 days'),
  ('ฉาบฉาย',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '192 days'),
  ('เล็ดลอดสายตา',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '193 days'),
  ('หายวับไปกับตา',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '194 days'),
  ('หายเป็นปลิดทิ้ง',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '195 days'),
  ('บรรเทาเบาบางลง',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '196 days'),
  ('ลบล้าง',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '197 days'),
  ('เสื่อมเสีย',null,'c5','อาการและทิศทางของอารมณ์',null,null,true,now() - interval '198 days'),
  ('ให้รู้แล้วรู้รอด',null,'c5','สำนวนและคำเปรียบเปรย','รู้แล้วรู้รอด',null,true,now() - interval '199 days'),
  ('จะให้นิ่งเฉยอยู่ได้อย่างไร',null,'c5','สำนวนและคำเปรียบเปรย','นิ่งเฉย',null,true,now() - interval '200 days'),
  ('ความลับแดงออกมา',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '201 days'),
  ('จับต้นชนปลายไม่ถูก',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '202 days'),
  ('เชื้อไม่ทิ้งแถว',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '203 days'),
  ('คว้าน้ำเหลว',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '204 days'),
  ('เป็นเรื่องเป็นราว',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '205 days'),
  ('เหลือบ่ากว่าแรง',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '206 days'),
  ('นิสัยใจคอ',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '207 days'),
  ('จุดพลิกผัน',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '208 days'),
  ('ต้นตอ',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '209 days'),
  ('มูลความจริง',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '210 days'),
  ('มีลู่ทาง',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '211 days'),
  ('วาระสุดท้าย',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '212 days'),
  ('หายนภัย',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '213 days'),
  ('จริงดังคาด',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '214 days'),
  ('ม่านหมอก','ความคลุมเครือ','c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '215 days'),
  ('เรื่องพรรค์นั้น',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '216 days'),
  ('สารพัด',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '217 days'),
  ('ประสบเคราะห์กรรม',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '218 days'),
  ('ลอยคว้างอยู่ในความทรงจำ',null,'c5','สำนวนและคำเปรียบเปรย','ลอยคว้าง',null,true,now() - interval '219 days'),
  ('ฝังแน่นอยู่ในใจไม่มีวันเลือนหาย',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '220 days'),
  ('ติดตรึงอยู่ในใจ',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '221 days'),
  ('ถอนรากถอนโคน',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '222 days'),
  ('ยัดเยียด',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '223 days'),
  ('ตวัดหาง','สายตา/ท่าที','c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '224 days'),
  ('ปากที่อ้ากว้าง','ตกใจ','c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '225 days'),
  ('ฆาตกรกระหายเลือด',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '226 days'),
  ('ขนานนามคนร้าย',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '227 days'),
  ('ตาถั่ว',null,'c5','สำนวนและคำเปรียบเปรย',null,null,true,now() - interval '228 days'),
  ('ขับเน้น',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '229 days'),
  ('เหมือนกันเปี๊ยบ',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '230 days'),
  ('ธรรมดาสามัญ',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '231 days'),
  ('ลึกลับซ่อนเร้น',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '232 days'),
  ('ครึกโครม',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '233 days'),
  ('รุนแรง',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '234 days'),
  ('พิลึกพิลั่น',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '235 days'),
  ('สภาพที่วิปริตผิดธรรมชาติ',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '236 days'),
  ('เรื่องคอขาดบาดตาย',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '237 days'),
  ('เอาเป็นเอาตาย',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '238 days'),
  ('อย่างใจจดใจจ่อ',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '239 days'),
  ('ประมาทเลินเล่อ',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '240 days'),
  ('ดันทุรัง',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '241 days'),
  ('เหลวไหลไร้สาระ',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '242 days'),
  ('ทวีความรุนแรง',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '243 days'),
  ('กระหน่ำ',null,'c5','เน้นน้ำหนัก',null,null,true,now() - interval '244 days'),
  ('สตาร์ตรถ',null,'c6','คำทับศัพท์',null,null,true,now() - interval '245 days'),
  ('เวอร์','มาจาก Over ใช้ในภาษาพูด','c6','คำทับศัพท์',null,null,true,now() - interval '246 days'),
  ('โทร.','จุดหลังคำย่อ','c6','คำทับศัพท์',null,null,true,now() - interval '247 days'),
  ('ช็อก','Shock','c6','คำทับศัพท์',null,null,true,now() - interval '248 days'),
  ('ล็อก','Lock','c6','คำทับศัพท์',null,null,true,now() - interval '249 days'),
  ('แข็งกร้าว',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '250 days'),
  ('เข้มงวดกวดขัน',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '251 days'),
  ('เด็กหัวรั้น',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '252 days'),
  ('ท่าทางแข็งกระด้าง',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '253 days'),
  ('วางท่าน่าเกรงขาม',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '254 days'),
  ('จองหอง',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '255 days'),
  ('เจ้ากี้เจ้าการ',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '256 days'),
  ('ดื้อดึง',null,'c7','นิสัยแข็งกร้าว/ดื้อดึง',null,null,true,now() - interval '257 days'),
  ('ล่อกแล่ก',null,'c7','นิสัยขี้กลัว/ไม่มั่นคง',null,null,true,now() - interval '258 days'),
  ('ใจปลาซิว','ขี้กลัว','c7','นิสัยขี้กลัว/ไม่มั่นคง',null,null,true,now() - interval '259 days'),
  ('คลอนแคลน','จิตใจไม่มั่นคง','c7','นิสัยขี้กลัว/ไม่มั่นคง',null,null,true,now() - interval '260 days'),
  ('ประพฤติตัว',null,'c7','นิสัยการวางตัว',null,null,true,now() - interval '261 days'),
  ('เจียมเนื้อเจียมตัว',null,'c7','นิสัยการวางตัว',null,null,true,now() - interval '262 days'),
  ('สงบเสงี่ยม',null,'c7','นิสัยการวางตัว',null,null,true,now() - interval '263 days');
